# ~/.config/starship.toml

add_newline = true

# [character]
# success_symbol = '[ï”](bold green)'
# error_symbol = '[âœ—](bold red)'

format = """$all"""

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[bun]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[c]
symbol = "î˜ "
format = '\[[$symbol($version(-$name))]($style)\]'

[cmd_duration]
format = '\[[î‹ $duration]($style)\]'

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "
format = '\[[$symbol($version)]($style)\]'

[directory]
read_only = " ï““"

[docker_context]
symbol = "ïŒˆ "

[elixir]
format = '\[[$symbol$context]($style)\]'
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = "ï˜ "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
symbol = "ó°› "

[nim]
symbol = "î™· "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
disabled = true
format = '\[[$symbol($version)]($style)\]'
symbol = "îœ˜ "

[package]
format = '\[[$symbol$version]($style)\]'
symbol = "ó°— "

[php]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "îˆµ "

[spack]
symbol = "ğŸ…¢ "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "î¨ "

[sudo]
format = '\[[as $symbol]\]'

[time]
disabled = true
format = '\[[$time]($style)\]'
time_format = '%T'
utc_time_offset = '+7'
time_range = '04:43:00-21:00:00'

[gradle]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[kotlin]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[username]
format = '\[[$user]($style)@'

[hostname]
ssh_only = true
format = '[$hostname](bold green)\] '
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false

[zig]
format = '\[[$symbol($version)]($style)\]'
